mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/insane_optimist.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/topless_computing.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/govuk_contracting.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/basic_seo.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/the_break.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/ducttapeOrReplace.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/likelawyers.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/meshNetworksAndMooresLaw.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/futureshifts.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/gold.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/agile_estimation.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/booklist.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/alwaysgoodships.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/freewifi.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/learningDeepLearning.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/hiring_ringers.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/cybersecuritykerfuffle.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/HNdisaster.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/slowcodemovement.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/notwrong.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/thecodeisthedesign.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/feynman.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/MaleAndFemaleSoftwareDevelopment.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/PokemonGoAndPrivacy.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/not_giving_up.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/specialSnowflake.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/interview_patrickmacandrew.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/ibmadverts.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/regulationandglobalisation.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/flowcontrol.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/python_warts.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/the_new_literacy.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/columbus.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/algorithmstoliveby.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/bothPythons.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
mv /home/pbrian/projects/mikadoCMS/mikadocms/data/mikadosoftware.com/orig/articles/why.rst /home/pbrian/projects/devmanual/docs/chapters/weeds/
